-- FUNÇÕES DE MANIPULAÇÃO DE DATAS. OBTENDO PARTES DE UMA DATA
-- SELECIONE O NOME, DIA DE NASCIMENTO, MES DE NASCIMENTO E ANO DE NASCIMENTO
-- DOS FUNCIONARIOS, A IDADE E SALARIO (BR). CONSIDERE SOMENTE FUNCIONARIOS ATIVOS
-- ORDENE POR IDADE E NOME.

SELECT 
NOME, 
-- DATEPART(DAY,DATA_NASCIMENTO),
DAY(DATA_NASCIMENTO) DIA, --PEGA SOMENTE O DIA DE UMA DATA
MONTH(DATA_NASCIMENTO) MES,--PEGA SOMENTE O MES DE UMA DATA
YEAR(DATA_NASCIMENTO) ANO,--PEGA SOMENTE O ANO DE UMA DATA
DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE()) IDADE, --FAZ O CALCULO DE DIFERENÇA DE IDADE
FORMAT(SALARIO,'C','PT-BR') SALARIO -- FAZ A FORMATAÇÃO DE SALARIO PARA REAL BR
FROM FUNCIONARIO
WHERE ATIVO = 1
ORDER BY IDADE, NOME;