-- ALUNO: FELIPE ADRIAN LOURENÇO BARBISAN
-- CURSO: 4º AMS(ADS)
USE CONSTRUTORA;
GO
SELECT * FROM FUNCIONARIO;
SELECT * FROM DEPENDENTE;
SELECT * FROM PROJETO;
SELECT * FROM FUNCIONARIO_PROJETO;
-- 1 -  FAÇA UM UPDATE PARA INATIVAR OS FUNCIONÁRIOS. CONSIDERE SOMENTE
-- FUNCIONÁRIOS ATIVOS DO SEXO MASCULINO QUE NÃO SEJAM DA CIDADE DE TAQUARITINGA,
-- QUE TENHAM IDADE MENOR OU IGUAL A 28 ANOS E QUE NÃO TENHAM NASCIDO NO MESES
-- DE MARÇO A JULHO.

UPDATE FUNCIONARIO SET ATIVO = 0 WHERE ATIVO = 1 AND SEXO = 'M' AND CIDADE != 'Taquaritinga' AND DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE())<=28 AND MONTH(DATA_NASCIMENTO) BETWEEN 3 AND 7;

-- 2 - APRESENTE O NOME DO FUNCIONÁRIO, A IDADE, CPF, EMAIL, SALARIO (BR), DATA_NASCIMENTO (BR),
-- CIDADE E UF. CONSIDERE SOMENTE FUNCIONÁRIOS RESIDENTES NAS CID. DE CATANDUVA OU TAQUARITINGA,
-- ESTADO DE SP, E QUE TENHAM 26 ANOS OU MAIS. ORDENE ORDEM DECRESCENTE DE NOME.

SELECT NOME,DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE()) IDADE,CPF,EMAIL,FORMAT(SALARIO,'C','pt-br') SALARIO,FORMAT(DATA_NASCIMENTO,'d','pt-br') DATA_NASC,CIDADE,UF FROM FUNCIONARIO WHERE CIDADE = 'Taquaritinga' OR CIDADE = 'Catanduva' AND UF = 'SP' AND DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE())>=26 ORDER BY NOME DESC;

-- 3 APRESENTE O NOME DO DEPENDENTE, DT DE NASCIMENTO, A IDADE, O PARENTESCO, E O  CÓDIGO
-- DO FUNCIONÁRIO RESPONSÁVEL. CONSIDERE SOMENTE PARENTESCO "FILHO" OU  FILHA". ORDENE POR
-- DATA DE NASCIMENTO (DECRESCENTE)  E NOME (CRESCENTE).

SELECT NOME NOME_DO_DEPENDENTE,FORMAT(DATA_NASCIMENTO,'d','pt-br') DATA_NASC, DATEDIFF(YEAR,DATA_NASCIMENTO,GETDATE()) IDADE, COD_FUNCIONARIO CÓDIGO_DO_FUNCIONÁRIO_RESPONSÁVEL FROM DEPENDENTE WHERE PARENTESCO = 'Filho' OR PARENTESCO = 'Filha' ORDER BY DATA_NASC DESC , NOME ASC;

-- 4 - APRESENTE O CÓDIGO DO PROJETO, O NOME, A DATA DE INÍCIO, DATA DE TÉRMINO E VALOR.
-- CONSIDERE SOMENTE PROJETOS INICIADOS A PARTIR DO DIA 01/01/2025, QUE TENHAM O VALOR
-- DEFINIDO. ORDENE POR NOME DE PROJETO.

SELECT CODIGO, NOME, DATA_INICIO, DATA_TERMINO,FORMAT(VALOR,'C','pt-br') VALOR FROM PROJETO WHERE DATA_INICIO >= '2025-01-01' AND VALOR IS NOT NULL ORDER BY NOME ASC;

-- 5 - FAÇA UM DELETE QUE REMOVA TODOS OS VINCULOS DE PROJETO (TABELA FUNCIONARIO_PROJETO)
-- ONDE A QUANTIDADE DE HORAS TRABALHADAS FOR INFERIOR A 100, E A DATA DE ENTRADA
-- TIVER OCORRIDO A MENOS DE 100 DIAS E A DATA DE SAIDA FOR NULA

DELETE FROM FUNCIONARIO_PROJETO WHERE NUM_HORAS_TRAB <= 100 AND DATEDIFF(DAY,DATA_ENTRADA,GETDATE()) < 100 AND DATA_SAIDA IS NULL