-- CREATE DATABASE BD_EMPRESA; 
USE BD_EMPRESA;
GO
CREATE TABLE FUNCIONARIO(
    CODIGO INT NOT NULL IDENTITY(1,1),
    NOME VARCHAR(50) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    CPF CHAR(11) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    SEXO CHAR(1) NOT NULL,
    DATA_HORA_CADASTRO DATETIME NOT NULL DEFAULT GETDATE(),
    ATIVO BIT NOT NULL DEFAULT 1,
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(CODIGO),
    CONSTRAINT UQ_FUNCIONARIO_CPF UNIQUE(CPF),
    CONSTRAINT UQ_FUNCIONARIO_EMAIL UNIQUE(EMAIL),
    CONSTRAINT CK_FUNCIONARIO_SEXO CHECK(SEXO IN('F','M')),
    CONSTRAINT CK_FUNCIONARIO_CPF CHECK(LEN(CPF)=11)
);
GO
SELECT * FROM FUNCIONARIO;