CREATE DATABASE LOCADORA;

USE LOCADORA;

CREATE TABLE VEICULO(
    CODIGO INT NOT NULL IDENTITY(1,1),
    PLACA CHAR(7) NOT NULL,
    MARCA VARCHAR(50) NOT NULL,
    MODELO VARCHAR(100) NOT NULL,
    ANO INT NOT NULL,
    VALOR_DIARIA FLOAT NOT NULL,
    KM FLOAT NOT NULL,
    CONSTRAINT PK_VEICULO PRIMARY KEY(CODIGO),
    CONSTRAINT UQ_VEICULO_PLACA UNIQUE(PLACA),
    CONSTRAINT CK_VEICULO_PLACA CHECK(LEN(PLACA) = 7),
    CONSTRAINT CK_VEICULO_ANO CHECK(ANO > (YEAR(GETDATE()) - 10) AND ANO <= YEAR(GETDATE())) 
);

CREATE TABLE CLIENTE(
    CODIGO INT NOT NULL IDENTITY(1,1),
    NOME VARCHAR(40) NOT NULL,
    LOGRADOURO VARCHAR(100) NOT NULL,
    BAIRRO VARCHAR(100) NOT NULL,
    CIDADE VARCHAR(50) NOT NULL,
    UF CHAR(2) NOT NULL,
    CEP INT NOT NULL,
    CELULAR INT NOT NULL,
    EMAIL VARCHAR(200) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    CPF INT NOT NULL,
    CONSTRAINT PK_CLIENTE PRIMARY KEY(CODIGO),
    CONSTRAINT CK_CLIENTE_UF CHECK (UF IN ('AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MT', 'MS', 'MG', 'PA', 'PB', 'PR', 'PE', 'PI', 'RJ', 'RN', 'RS', 'RO', 'RR', 'SC', 'SP', 'SE', 'TO')),
    CONSTRAINT CK_CLIENTE_CELULAR CHECK(LEN(CELULAR) = 11),
    CONSTRAINT CK_CLIENTE_IDADE CHECK(YEAR(DATA_NASCIMENTO) <= (YEAR(GETDATE()) -  18)),
    CONSTRAINT UQ_CLIENTE_EMAIL UNIQUE(EMAIL),
    CONSTRAINT UQ_CLIENTE_CELULAR UNIQUE(CELULAR),
    CONSTRAINT UQ_CLIENTE_CPF UNIQUE(CPF),
    CONSTRAINT CK_CLIENTE_CPF CHECK(LEN(CPF) = 11),
    CONSTRAINT CK_CLIENTE_CEP CHECK(LEN(CEP) = 8)

);

CREATE TABLE LOCACAO(
    CODIGO INT NOT NULL IDENTITY(1,1),
    COD_VEICULO INT NOT NULL,
    COD_CLIENTE INT NOT NULL,
    DATA_HORA_RETIRADA DATETIME NOT NULL,
    DATA_HORA_DEVOLUCAO DATETIME NULL,
    VALOR_TOTAL FLOAT NULL,
    CONSTRAINT PK_LOCACAO PRIMARY KEY(CODIGO),
    CONSTRAINT FK_VEICULO FOREIGN KEY(COD_VEICULO) REFERENCES VEICULO(CODIGO),
    CONSTRAINT FK_CLIENTE FOREIGN KEY(COD_CLIENTE) REFERENCES CLIENTE(CODIGO),
    CONSTRAINT CK_LOCACAO_DATA_HORA_DEVOLUCAO CHECK(DATA_HORA_DEVOLUCAO >= DATA_HORA_RETIRADA)
)